name: Go API Diff
on: 
  pull_request:
jobs:
  go-apidiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Do not bump go version joelanford/go-apidiff is build with go 1.18
    - uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - uses: joelanford/go-apidiff@main
