name: Update GKE Operator in rancher/charts
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to use for GitHub action workflow"
        required: true
        default: "master"
      charts_ref:
        description: "Submit PR against the following rancher/charts branch (e.g. dev-v2.7)"
        required: true
        default: "dev-v2.7"
      prev_gke_operator:
        description: "Previous GKE operator version (e.g. 1.1.0-rc2)"
        required: true
        default: ""
      new_gke_operator:
        description: "New GKE operator version"
        required: true
        default: ""
      prev_chart:
        description: "Previous Rancher Chart version (e.g. 101.1.0)"
        required: true
        default: ""
      new_chart:
        description: "New Rancher Chart version"
        required: true
        default: ""
      should_replace:
        description: "Should the old GKE operator version be replaced/removed? (e.g. true in case of release candidate bumps)"
        required: true
        default: "true"

jobs:
  create-rancher-charts-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.inputs.ref}}
          path: gke-operator
      - name: Checkout rancher/charts
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: rancher/charts
          ref: ${{github.event.inputs.charts_ref}}
          path: charts
      - name: Run release script
        run: ./gke-operator/.github/scripts/update-rancher-charts.sh ${{github.event.inputs.prev_gke_operator}} ${{github.event.inputs.new_gke_operator}} ${{github.event.inputs.prev_chart}}  ${{github.event.inputs.new_chart}}  ${{github.event.inputs.should_replace}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.CI_BOT_TOKEN}}
          push-to-fork: highlander-ci-bot/charts
          title: 'Update GKE operator to v${{github.event.inputs.new_gke_operator}}'
          body: |
            Update GKE operator to v${{github.event.inputs.new_gke_operator}}

            Changelog: https://github.com/rancher/gke-operator/releases/tag/v${{github.event.inputs.new_gke_operator}}

            cc @rancher/highlander
          branch-suffix: timestamp
          base: ${{github.event.inputs.charts_ref}}
          path: ./charts/
